### ISSUE TITLE
terra SpatVector on plots?

### ISSUE THREAD

**Issue by courtiol** [oscarperpinan/rastervis#101]
Is it possible to add points or polygons on a plot produced with rasterVis without using sp?
Indeed, terra has SpatVector objects to handle points or polygons but I don't see how to add those under a lattice framework.

Here is a toy example using polygons:

``` r
library(rasterVis)
#> Loading required package: lattice

## prepare objects to be plotted
elev <- terra::rast(system.file("ex/elev.tif", package = "terra"))
country_poly_sp <- rnaturalearth::ne_countries(scale = 10, returnclass = "sp")
country_poly_terra <- terra::vect(rnaturalearth::ne_countries(scale = 10, returnclass = "sp"))

## rasterVis plot using sp for polygons
levelplot(elev, margin = FALSE) +
  latticeExtra::layer(sp::sp.lines(country_poly_sp))
```

![](https://i.imgur.com/Mq2Nw0D.png)

``` r

## non-rasterVis plot using terra
terra::plot(elev)
terra::polys(country_poly_terra)
```

![](https://i.imgur.com/DJUvkeD.png)

``` r

## rasterVis plot using terra for polygons?
#levelplot(elev, margin = FALSE) + ?
```

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by wenzmo** [comment]
I tried this but the polygon seemed to be not closed in the end. 
```{r}
data <- data.frame(x = terra::crds(country_poly_terra, df = TRUE)$x,
                   y = terra::crds(country_poly_terra, df = TRUE)$y)


data <- rbind(data, data[1,])


levelplot(elev, margin = FALSE, panel=function(...){
  panel.levelplot(...)
  panel.polygon(data)})
```
![levelplot_terra](https://user-images.githubusercontent.com/38684163/215087001-505d4d01-25ab-42a5-a962-04d3e6a8d1cd.png)

But I think it's a good starting point

**Comment by oscarperpinan** [comment]
> Is it possible to add points or polygons on a plot produced with rasterVis without using sp?

The `levelplot` methods of `rasterVis` are based on the `levelplot` function of the `lattice` package. The `sp` package includes several functions to display points, lines and polygons based on `lattice` functions. There is no problem to use a different function from another package as long as it is compatible with the graphics produced by `lattice`.

> Indeed, terra has SpatVector objects to handle points or polygons but I don't see how to add those under a lattice framework.

The functions provided by `terra` use `base` graphics. They are not compatible with `lattice`.

**Comment by oscarperpinan** [comment]
By the way, if you need to plot polygons you'd better use the `sp.polygons` function.

**Comment by courtiol** [comment]
Whom do you think we shall motivate  to implement a way to directly handle lines and points from terra objects in lattice?
terra replaces the need for both raster and sp, if it were not for this plotting issue.

**Comment by oscarperpinan** [comment]
Well, me, I guess. 

A basic implementation is not difficult to write. For example:

```
library(lattice)
library(latticeExtra)
library(terra)
library(rasterVis)

f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)

r <- rast(v)
values(r) <- 1:ncell(r)

panel.polys <- function(x, col = 1, fill = "transparent", ...)
{
    ## Adapted from terra::polys
    xy <- x@ptr$polygonsList()
    for (i in 1:length(xy)) {
        for (j in seq_along(xy[[i]])) {
            ## Adapted from sp::sppanel por SpatialPolygons
            grid::grid.polygon(xy[[i]][[j]][[1]], xy[[i]][[j]][[2]],
                               default.units = "native",
                               gp = grid::gpar(col = col, fill = fill, ...))
        }
    }
}

levelplot(r) + layer(panel.polys(v, col = "white"))
```

However, a more robust and user-friendly implementation requires time, and I don't know when I will have it. Any help is appreciated ;-)

**Comment by courtiol** [comment]
Not sure it helps, but i create basic implementations for points and lines too:
```r
library(lattice)
library(latticeExtra)
library(terra)
library(rasterVis)

f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)

r <- rast(v)
values(r) <- 1:ncell(r)

panel.points2 <- function(x, pch = 1, ...) {
  ## Adapted from terra::points
  xy <- terra::crds(x)
  grid::grid.points(x = xy[, 1], y = xy[, 2],
                    default.units = "native",
                    pch = pch,
                    gp = grid::gpar(...))
}

panel.lines2 <- function(x, ...) {
  ## Adapted from terra::lines
  xy <- l@ptr$linesNA()
  names(xy) <- c("x", "y")
  grid::grid.lines(x = xy$x, y = xy$y,
                   default.units = "native",
                   gp = grid::gpar(...))
}

p <- terra::as.points(v)
levelplot(r, margin = FALSE) + layer(panel.points2(p, col = "white"))

l <- terra::as.lines(v)
levelplot(r, margin = FALSE) + layer(panel.lines2(l, col = "white", lty = 3))
```

**Comment by courtiol** [comment]
I am not sure what you have in mind with 

>  a more robust and user-friendly implementation

but I noticed that `lattice::panel.points()` and `lattice::panel.lines()` now point to S3 generics (`lattice::llines` and `lattice::lpoints`).

So perhaps, we could simply create new methods for these generics `llines.SpatVector` and `lpoints.SpatVector`.

Confusingly,  `lattice::panel.polygon()` calls `lattice::lpolygon()` which is not a generic.. but perhaps we could ask the `lattice` maintainer to turn this function into a generic so we can proceed in a similar fashion.

What do you think @oscarperpinan ?

**Comment by courtiol** [comment]
Just in case, I have drafted a PR for adding the missing generics in lattice: https://github.com/deepayan/lattice/pull/30

**Comment by rhijmans** [comment]
For terra, I prefer that other packages use the formal R interface, and not directly call the "raw" interface as in `x@ptr$function` because that will break much more often. For example, if an argument is added, the R method normally gets a default that does not change the behavior; but the call to `x@ptr$function` would fail. 

In this case, there was no formal R interface, and I have now added that.  Instead of `x@ptr$linesNA()` and `x@ptr$polygonsList()` you can now use `crds(x, list=TRUE)`

**Comment by courtiol** [comment]
Thanks a lot @rhijmans, we will make sure to use your new extractors rather than relying on the internal structure of the objects.

**Comment by oscarperpinan** [comment]
Thanks @courtiol for your code, and thanks @rhijmans for the interfaces.

The functions would be: 

```
lpoints.SpatVector <- function(x, ...) {
  xy <- terra::crds(x, df = TRUE)
  lattice::lpoints(xy, ...)
}

llines.SpatVector <- function(x, ...) {
  xy <- crds(x, list=TRUE)
  names(xy) <- c("x", "y")
  lattice::llines(xy, ...)
}

lpolygon.SpatVector <- function(x, ...) {
  xy <- crds(x, list=TRUE)
  for (i in seq_along(xy)) {
    for (j in seq_along(xy[[i]])) {
      lattice::lpolygon(x = xy[[i]][[j]][[1]], xy[[i]][[j]][[2]], ...)
    }
  }
}

```

With this example:

```
library(lattice)
library(latticeExtra)
library(terra)
library(rasterVis)

f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)

r <- rast(v)
values(r) <- 1:ncell(r)

pts <- terra::as.points(v)
levelplot(r, margin = FALSE) +
    layer(panel.points(pts, col = "white"))

lns <- terra::as.lines(v)
levelplot(r, margin = FALSE) +
    layer(panel.lines(lns, col = "white", lty = 3))

## This part will work when the PR#30 is accepted in lattice
pols <- terra::as.polygons(v)
levelplot(r, margin = FALSE) +
    layer(panel.polygon(pols, border = "white", col = "transparent", lty = 3))

```

**Comment by courtiol** [comment]
Thanks a lot, yes that should do it.
I hope that @deepayan will comment on PR https://github.com/deepayan/lattice/pull/30 soonish :-)

**Comment by courtiol** [comment]
Minor edits to avoid crashes if `x` is NULL:
```r
lpoints.SpatVector <- function(x, ...) {
  if (is.null(x)) return(NULL)
  xy <- terra::crds(x, df = TRUE)
  lattice::lpoints(xy, ...)
}

llines.SpatVector <- function(x, ...) {
  if (is.null(x)) return(NULL)
  xy <- terra::crds(x, list=TRUE)
  names(xy) <- c("x", "y")
  lattice::llines(xy, ...)
}

lpolygon.SpatVector <- function(x, ...) {
  if (is.null(x)) return(NULL)
  xy <- terra::crds(x, list=TRUE)
  for (i in seq_along(xy)) {
    for (j in seq_along(xy[[i]])) {
      lattice::lpolygon(x = xy[[i]][[j]][[1]], xy[[i]][[j]][[2]], ...)
    }
  }
}
```

**Comment by courtiol** [comment]
There is still something that seems off @oscarperpinan, perhaps in our function or perhaps elsewhere. Not all polygons seem to be drawn. I am not sure why. Calling the simple `plot()` functions does not have this issue...

``` r
## projections for computation on a sphere
transfo <- "EPSG:32662"

## import oceans
oceans_sf <- rnaturalearth::ne_download(category = "physical", scale = "large",
                                        type = "ocean", returnclass = "sf")
#> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
#> which was just loaded, were retired in October 2023.
#> Please refer to R-spatial evolution reports for details, especially
#> https://r-spatial.org/r/2023/05/15/evolution4.html.
#> It may be desirable to make the sf package available;
#> package maintainers should consider adding sf to Suggests:.
oceans_terra <- terra::vect(oceans_sf[, 0])
oceans_terra <- terra::project(oceans_terra, transfo)

## import elevation raster
world_limits <- sf::st_bbox(oceans_sf)
worldelev_raster <- elevatr::get_elev_raster(locations = world_limits,
                                             z = 1, prj = transfo)
#> Mosaicing & Projecting
#> Note: Elevation units are in meters.
worldelev_terra <- terra::rast(worldelev_raster)
terra::crs(worldelev_terra) <- transfo

## plotting using a new method
lpolygon.SpatVector <- function(x, ...) {
  if (is.null(x)) return(NULL)
  xy <- terra::crds(x, list = TRUE)
  for (i in seq_along(xy)) {
    for (j in seq_along(xy[[i]])) {
      lattice::lpolygon(x = xy[[i]][[j]][[1]], xy[[i]][[j]][[2]], ...)
    }
  }
}

## PROBLEM: some continents covered by water...
rasterVis::levelplot(worldelev_terra, margin = FALSE) +
  latticeExtra::layer(lpolygon.SpatVector(oceans_terra, border = "yellow", col = "blue"))
```

![](https://i.imgur.com/k3h7QQT.png)

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by courtiol** [comment]
It is caused by the presence of NAs in polygons, and I don't know who to handle those...

**Comment by courtiol** [comment]
@rhijmans, could you please have a look? I tried for a while, but I am getting nowhere on the last problem...
I am starting to suspect that using `terra::crds` may not be the right choice when polygons refer to "holes".

**Comment by rhijmans** [comment]
`NaN`'s are used to separate the hole(s) from the ring they belong to. You could use something like `which(is.nan(x))` to find them. But perhaps the first question is (at least for me) what `lattice::lpolygon`  expects to identify a polygon hole.

**Comment by oscarperpinan** [comment]
As far as I can find, the relevant lines of code inside [`lattice::lpolygon`](https://github.com/deepayan/lattice/blob/2cb437dab814d93e8fce03427f1c9a939a05a346/R/miscellaneous.R#L233) are:
```
n <- length(xy$x)
w <- which(is.na(xy$x) | is.na(xy$y))
id.lengths <- diff(c(0, w, n))
``` 
and `id.lengths` is passed to `grid::grid.polygon` which interprets it  as "A numeric vector used to separate locations in ‘x’ and ‘y’ into multiple polygons".

**Comment by deepayan** [comment]
You probably want `grid.path()`; see <https://journal.r-project.org/archive/2012/RJ-2012-017/index.html>. I need to add a wrapper for this in lattice.

**Comment by courtiol** [comment]
Thanks @deepayan. Let's continue this here: https://github.com/deepayan/lattice/issues/36

**Comment by courtiol** [comment]
@oscarperpinan, the issue with the holes is now sorted out in lattice. So I think that we can close this issue.

**Comment by courtiol** [comment]
@oscarperpinan, since @deepayan implemented `lpolypath()`, do you think that we should have `lpolygon.SpatVector()` with `rule = "none"` and  `lpolypath.SpatVector()` with `rule = "winding"` for consistency with **lattice**? Or shall we stick to what we did so far?

**Comment by oscarperpinan** [comment]
In my opinion, we should be consistent with the R-spatial ecosystem. These packages provide functions for displaying lines, points and polygons. Thus, even if we implement an `lpolypath` method for `SpatVector`, it should be encoded into  `lpolygon`. 
Anyhow, I cannot understand the differences between `lpolypath` and `lpolygon`. I have tried the last examples in `xyplot::llines`  with both `panel.polypath` and `panel.polygon` and the results are the same.

```
     x <- c(.1, .5, .9, NA, .4, .5, .6, NA, .4, .6, .5)
     y <- c(.1, .8, .1, NA, .5, .4, .5, NA, .3, .3, .2)
     d <- data.frame(x = x, y = y)
    ## winding
     xyplot(y ~ x, data = d, panel = panel.polypath, rule = "winding", col = "grey")
     xyplot(y ~ x, data = d, panel = panel.polygon, rule = "winding", col = "grey")
    ## evenodd
     xyplot(y ~ x, data = d, panel = panel.polypath, rule = "evenodd", col = "grey")
     xyplot(y ~ x, data = d, panel = panel.polygon, rule = "evenodd", col = "grey")
```

**Comment by deepayan** [comment]
No difference. `lpolypath()` is the analog of `graphics::polypath()` and `lpolygon()` of `graphics::polygon()`. As a convenience, `lpolygon()` now just happens to have an extra `rule` argument which can make it call `grid.path()` instead of `grid.polygon()`. 

I think this makes sense here because the `NA`-based `polygon()` API is limited. `grid.path()` is more general (you can specify multiple paths, each with subpaths). But if that's needed, one should call `grid.path()` directly.

**Comment by courtiol** [comment]
Yes, the difference between `panel.polypath` and `panel.polygon` is just the default "rule" (`"winding `for the former and `"none"`" for the later). In sp, they constrain the rule internally and detect if the polygons have holes or not, so `sp.polygons` can draw holes via automatically calling `grid.path`. In contrast, in graphics and grid, the functions to draw holes have to be called explicitelly.

So we have 3 alternatives for rasterVis:

- fix the default rule to "winding" (or "evenodd") so that `lpolygon.spatVector()` draws holes: this is what we did until now; it is quite similar to sp behaviour but it introduces a discrepancy with lattice where `lpolygon.default()` considers `rule = "none"` by defaut.

- fix the default rule to "none" in `lpolygon.spatVector()` and let people know that they must change the rule argument to draw holes.

- fix the default rule to "none" in `lpolygon.spatVector()`, implement `lpolypath.spatVector()` and let people know they must use this function to draw holes. This is most consistent with grid and graphics.

I have no strong preferences. The easiest for naive users would be option 1. The more consistent with other packages would be option 3.

**Comment by oscarperpinan** [comment]
Another option is to set the default rule to "evenodd" but explicitly instead of internally:

```
lpolygon.SpatVector <- function(x, rule = "evenodd", ...) {
  if (is.null(x)) return(NULL)
  xy <- terra::crds(x, list = TRUE)
  for (i in seq_along(xy)) {
    for (j in seq_along(xy[[i]])) {
      lattice::lpolygon(x = xy[[i]][[j]][[1]], xy[[i]][[j]][[2]], rule = rule, ...)
    }
  }
}
```

**Comment by courtiol** [comment]
Yes, that could be a good idea that would allow for a short explanation in the documentation.
You pick, and I offer to help with whatever option you pick.

**Comment by rhijmans** [comment]
I cannot think of any situation in which you would want to ignore the holes. In that case it would make sense to remove them (`terra::fillHoles`). I suppose you can always provide the option, but I do not see a need for it.

**Comment by oscarperpinan** [comment]
Done.

**Comment by oscarperpinan** [comment]
Finally, package rasterVis_0.51.6.tar.gz is on its way to CRAN. Thanks for your help.
