### ISSUE TITLE
how to manipulate the xlim and ylim for vectorplot?

### ISSUE THREAD

**Issue by michael2482004** [oscarperpinan/rastervis#107]
Is there any methods to set the xlim and ylim for vectorplot()? 
 This is very useful to show the netCDF data. 
Many thanks

**Comment by oscarperpinan** [comment]
You can use `xlim` and `ylim`:

```
library(raster)
library(rasterVis)

proj <- CRS('+proj=longlat +datum=WGS84')

df <- expand.grid(x=seq(-2, 2, .01), y=seq(-2, 2, .01))
df$z <- with(df, (3*x^2 + y)*exp(-x^2-y^2))
r1 <- rasterFromXYZ(df, crs=proj)

vectorplot(r1, xlim = c(-1, 1), ylim = c(-1, 1))
```

**Comment by michael2482004** [comment]
Many thanks.&nbsp;


I recheck the code and found the error is that the layer() function was overlapped by ggplot2.


Regards,


Zhe&nbsp;


孙喆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oscarperpinan/rastervis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 晚上6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [oscarperpinan/rastervis] how to manipulate the xlim and ylim for vectorplot? (Issue #107)





 
You can use xlim and ylim:
 library(raster) library(rasterVis) proj <- CRS('+proj=longlat +datum=WGS84') df <- expand.grid(x=seq(-2, 2, .01), y=seq(-2, 2, .01)) df$z <- with(df, (3*x^2 + y)*exp(-x^2-y^2)) r1 <- rasterFromXYZ(df, crs=proj) vectorplot(r1, xlim = c(-1, 1), ylim = c(-1, 1))
