### ISSUE TITLE
Using stacked SpatRaster

### ISSUE THREAD

**Issue by thaisrosan** [oscarperpinan/rastervis#108]
Hi,

I'm changing my codes to use terra instead of raster. I have a couple of codes that use levelplot to plot some stacked rasters, which now need to be done by using rast_stack <- c(rast1, rast2) instead of stack() function.
However, I'm getting this error 'Error in eval(i, data, env) : object 'rast.1' not found' while trying to use levelplot with the stacked SpatRast using c(). Is there any solution for this?

Cheers,
Thais

**Comment by oscarperpinan** [comment]
Hello,

`c()` assigns the same name for all the layers, but each layer needs a unique name for levelplot:

```
library(terra)
library(rasterVis)

f <- system.file("ex/elev.tif", package="terra")
rt <- rast(f)
st <- c(rt, rt + 500, rt - 500)

set.names(st, c("r0", "rp500", "rm500"))

levelplot(st)
```
