### ISSUE TITLE
Does any one knows that how to remove background gray color when using gplot method in Rastervis?

### ISSUE THREAD

**Issue by bwtian** [oscarperpinan/rastervis#13]
r <- raster(system.file("external/test.grd", package="raster"))
s <- stack(r, r*2)
names(s) <- c('meuse', 'meuse x 2')

library(ggplot2)

theme_set(theme_bw())
gplot(s) + geom_tile(aes(fill = value)) +
    facet_wrap(~ variable) +
    scale_fill_gradient(low = 'white', high = 'blue') +
    coord_equal() +
    theme(
            plot.background = element_blank()
            ,panel.grid.major = element_blank()
            ,panel.grid.minor = element_blank()
            ,panel.border = element_blank()
            ,panel.background = element_blank())
![rplot11](https://cloud.githubusercontent.com/assets/890380/4554395/758ef47a-4ead-11e4-99e4-60b270216b0c.png)

**Comment by rmarrotte** [comment]
You can also do na.value = "transparent"
