### ISSUE TITLE
Legend for vectorplot

### ISSUE THREAD

**Issue by pascaloettli** [oscarperpinan/rastervis#17]
Hi Oscar,

Is it easy to add a (optional) legend to a vector plot? Typically, an arrow outside the frame giving a wind speed.

Best,
Pascal

**Comment by oscarperpinan** [comment]
Hi Pascal,

It is not very easy, but I think there is a solution. I will try to implement it as soon as possible.

Best

Oscar

**Comment by pascaloettli** [comment]
Hi Oscar,

Thank you.

Best,
Pascal

**Comment by pascaloettli** [comment]
Hi Oscar

As far as I understand, the `key.arrow` option uses `arrow` from the `grid` package. If I am not mistaken, the import of `arrow` from `grid` is missing in the `NAMESPACE` file.

Best,
Pascal

**Comment by oscarperpinan** [comment]
You are right. Fixed now. Thanks.
