### ISSUE TITLE
Legend for vectorplot doesn't appear when associated with levelplot

### ISSUE THREAD

**Issue by pascaloettli** [oscarperpinan/rastervis#18]
Hi Oscar,

Sorry to bother you again.

Please consider the following example. The `key.arrow` for `vectorplot` appears on the upper left corner when used alone. But when `vectorplot` and `levelplot` are used together, the `key.arrow` doesn't appear. Do yo think there is an easy solution to that problem?

Best
Pascal

    library(rasterVis)
    library(gridExtra)

    proj <- CRS('+proj=longlat +datum=WGS84')

    df <- expand.grid(x=seq(-2, 2, .01), y=seq(-2, 2, .01))
    df$z <- with(df, (3*x^2 + y)*exp(-x^2-y^2))
    r1 <- rasterFromXYZ(df, crs=proj)

    p1 <- 
      vectorplot(r1, , region = FALSE, key.arrow = list(size = 5, label = 'm/s'))

    p2 <- 
      levelplot(r1, margin = FALSE) +
      vectorplot(r1, , region = FALSE, key.arrow = list(size = 5, label = 'm/s'))

    grid.arrange(p1, p2, nrow = 1)

![rplot](https://cloud.githubusercontent.com/assets/6613954/5912870/9838de4c-a61d-11e4-8261-27e52df0bee3.png)

**Comment by oscarperpinan** [comment]
Hi,

You can use the `region` argument to display the background. For example:

```
vectorplot(r1, region = TRUE, key.arrow = list(size = 5, label = 'm/s'))
```

or with a different `Raster`:

```
vectorplot(r1, region = r2, key.arrow = list(size = 5, label = 'm/s'))
```

**Comment by pascaloettli** [comment]
Hi,

This only applies if the rasters have the same extent, which is not my case. And with your solution, I think I cannot tune neither the order of the layers nor the colorkey for the region. 

Best

**Comment by oscarperpinan** [comment]
Ok, then you have to use `as.layer` with `under = TRUE`:

```
pvc <- vectorplot(r1, region = FALSE,
                  key.arrow = list(size = 5, label = 'm/s'))

plv <- levelplot(r1, margin = FALSE)

pvc + as.layer(plv, under = TRUE)
```

**Comment by pascaloettli** [comment]
Oscar,

Sorry for bothering you, I should have use `under = TRUE` before.

Thank you,
Pascal

**Comment by oscarperpinan** [comment]
No problem!

Cheers.

**Comment by pascaloettli** [comment]
Oscar,

Sorry, too fast. No `colorkey` for `levelplot` appears.

I will see this later,
Cheers

**Comment by oscarperpinan** [comment]
Oh, yes, it's true.

Then try this:

```
pvc <- vectorplot(r1, region = FALSE,
                  key.arrow = list(size = 5, label = 'm/s'))

plv <- levelplot(r1, margin = FALSE)

## reuse the legend of vectorplot in levelplot
plv$legend$top <- pvc$legend$top

plv + pvc
```

**Comment by pascaloettli** [comment]
Thank you, it now works.

![rplot](https://cloud.githubusercontent.com/assets/6613954/5933983/bf0ac226-a70b-11e4-82a1-19a189dc2f71.png)
