### ISSUE TITLE
Different plot with rasterVis using raster_2.3-12 and raster_2.3-24

### ISSUE THREAD

**Issue by pascaloettli** [oscarperpinan/rastervis#19]
Hi Oscar,

I just noticed a difference using, for example, `levelplot` on NetCDF read with the `raster` package. With `raster_2.3-12`, the coordinates are correctly displayed (N-S, W-E), but not with `raster_2.3-24`, the most recent version. Do you have an idea to explain this difference?

Best
Pascal

raster_2.3-12:
![rplot01](https://cloud.githubusercontent.com/assets/6613954/5933865/e261b4de-a709-11e4-9523-d08bb19ebcf9.png)

raster_2.3-24:
![rplot02](https://cloud.githubusercontent.com/assets/6613954/5933869/f63327e0-a709-11e4-8686-f6371878fc04.png)

**Comment by oscarperpinan** [comment]
It seems that  raster does not recognize the proj4 information of the file, and thus sets it to NA. I will check it later.

**Comment by pascaloettli** [comment]
Right, I didn't notice this. Good point.

**Comment by oscarperpinan** [comment]
I think it is due to [this commit](https://r-forge.r-project.org/scm/viewvc.php/pkg/raster/R/netCDFtoRasterCD.R?root=raster&r1=3028&r2=3078&pathrev=3078). You may report this problem as a bug to Robert [here](https://r-forge.r-project.org/tracker/?group_id=294).
