### ISSUE TITLE
Issue in help page

### ISSUE THREAD

**Issue by pascaloettli** [oscarperpinan/rastervis#23]
Using `rasterVis` version `0.36`.
When comparing the [original `.Rd`](https://github.com/oscarperpinan/rastervis/blob/master/man/hovmoller-methods.Rd) file and the compiled help page of `hovmoller` function, two differences lead to error when trying to run the examples:

1. `listFich <- dir(pattern='\\.nc')` became `listFich <- dir(pattern='\.nc')` in `?hovmoller`

2. `month <- function(x)format(x, '%m')` became `month <- function(x)format(x, '` in `?hovmoller`

What could explain these differences?

**Comment by oscarperpinan** [comment]
Thanks. I forgot to include the escape character '\'.
