### ISSUE TITLE
FUN.margin is deprecated in contourplot

### ISSUE THREAD

**Issue by pascaloettli** [oscarperpinan/rastervis#27]
R version `3.2.2`
rasterVis version `0.37`
lattice version `0.20-33`

A warning appears while using `contourplot` function.

    library(rasterVis)
    f <- system.file("external/test.grd", package="raster")
    r <- raster(f)
    contourplot(r, labels=list(cex=0.4), cuts=12)
    Warning in .local(x, data, ...) :
      FUN.margin is deprecated. Use margin as a list instead.
    Warning in .local(x, data, ...) :
      axis.margin is deprecated. Use margin as a list instead.

**Comment by oscarperpinan** [comment]
Thanks. Fixed now.
