### ISSUE TITLE
Interrupting levelplot of a large stack kills RStudio

### ISSUE THREAD

**Issue by johnbaums** [oscarperpinan/rastervis#33]
Given a large `RasterStack`, plotting with the default `raster` `plot` method can be interrupted with `Esc`.

When I plot with `levelplot`, interrupting with `Esc` halts plotting but the console remains active indefinitely (okay, maybe the length of time can be defined... I lost patience). This happens when plotting to the RStudio gui device, but not when plotting to, e.g., an `x11` device (which allows me to interrupt plotting, returning immediately to the console).

Here's an example that reproduces the problem, on my system at least...

```
library(rasterVis)
s <- stack(replicate(10, raster(matrix(runif(1e6), 1e3))))
levelplot(s)
# now hit Escape after plotting has commenced
# Eventually, kill the RStudio process and cry about your lost workspace
```

But no problem with the following:

```
x11()
levelplot(s)
# now hit Escape and get on with what you were doing, no worries
```

Similarly, no problem if the stack is small:

```
s <- stack(replicate(10, raster(matrix(runif(100), 10))))
levelplot(s)
# Hit escape really fast to beat the plotting
```

I'm using RStudio Version 0.99.837 under Windows 8 x64. My `sessionInfo()` is:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rasterVis_0.38      latticeExtra_0.6-26 RColorBrewer_1.1-2  lattice_0.20-33     raster_2.4-20       sp_1.2-1           

loaded via a namespace (and not attached):
[1] zoo_1.7-12     parallel_3.2.2 tools_3.2.2    hexbin_1.27.1  Rcpp_0.12.2    grid_3.2.2
```

**Comment by oscarperpinan** [comment]
I will have to install RStudio to test this issue. Meanwhile, could you test this?:

```
s <- stack(replicate(10, raster(matrix(runif(1e6), 1e3))))
df <- as.data.frame(s)
xy <- xyFromCell(s, seq_len(ncell(s)))
df <- cbind(df, xy)

ff <- as.formula(paste(paste(names(df), collapse = '+'),
                       'x * y', sep = '~'))

levelplot(ff, data = df)
```

**Comment by johnbaums** [comment]
Cancelling `levelplot(ff, data=df)` seems to work _sometimes_. I've tested a few times (and crashed a few times) - it seems like it'll cancel if I hit escape within the first 5 seconds or so...

**Comment by oscarperpinan** [comment]
Ok. I think there is nothing here related with `rasterVis::levelplot` or `lattice::levelplot`. In my opinion, you should contact the [RStudio support team](https://support.rstudio.com/hc/en-us/articles/200488518-RStudio-Crashed).

**Comment by johnbaums** [comment]
Ok, will do - thanks for checking it out.
