### ISSUE TITLE
No legend title when saving plot to a variable

### ISSUE THREAD

**Issue by thiagoveloso** [oscarperpinan/rastervis#34]
This code works for adding a legend title to an active plot:

```
library(rasterVis)

f <- system.file("external/test.grd", package="raster")
r <- raster(f)
levelplot(r, margin=F)
trellis.focus("legend", side="right", clipp.off=TRUE, highlight=FALSE)
grid::grid.text(expression(m^3/m^3), 0.2, 0, hjust=0.3, vjust=1.5)
trellis.unfocus()
```

But it doesn't work for a plot saved to a variable, e.g.: `p1 <- levelplot(r, margin=F)`.

This feature would be really useful, for example, for adding data units to the plot's legend.

One possible solution, achieved by changing some fundamental levelplot code, is suggested here: http://stackoverflow.com/questions/36874897/r-how-to-add-legend-title-to-levelplot-saved-to-a-variable

**Comment by oscarperpinan** [comment]
Now it is possible to add a title:

`levelplot(r, colorkey = list(title = "[m]"))`
and modify its graphical parameters:
```
levelplot(r, margin = FALSE,
             colorkey = list(title = "[m]",
                             title.gpar = list(cex = 1,
                                               font = 2,
                                               col = 'red')
                             ))
```
Comments are welcome!

**Comment by thiagoveloso** [comment]
Awesome! I can even include super/subscripts, i.e.:

`levelplot(r, colorkey = list(title = expression(paste("W ", m^2), sep="")))`

Thank you so much, Oscar. I consider this issue closed.

**Comment by oscarperpinan** [comment]
Thanks!
