### ISSUE TITLE
streamlines for uv wind field

### ISSUE THREAD

**Issue by isezen** [oscarperpinan/rastervis#35]
Can you give a simple example how to plot a streamline for a given uv components of a wind field? I tried  all of the examples on the net but I couldn't manage to plot a meaningful streamlines of uv wind field. I get only points on a dark background. For a simple start, assume, we have a 2 matrices of u and v fields. then what?

**Comment by oscarperpinan** [comment]
Try this:

```
library(meteoForecast)
library(rasterVis)

u <- getRaster('u', day = '2016-04-01', frames = 1)
v <- getRaster('v', day = '2016-04-01', frames = 1)

uv <- stack(u, v)
```
With the default background:
```
streamplot(uv, isField = 'dXY',
           droplet = list(pc = 1))
```
Or with a raster background:
```
myTheme <- streamTheme(region = brewer.pal(n = 9, 'Greys'))

streamplot(uv, isField = 'dXY',
           droplet = list(pc = 1),
           par.settings = myTheme)
```

**Comment by isezen** [comment]
Thanks for the response. My problem actually was having a very coarse grid resolution. I had a [1:23, 1:21] u and v matrices and resulting streamplot was meaningless (a couple of random points on a black bacground). I first thought that streamplot function is independent from the grid resolution but it is not. I used akima bicubic interpolation to increase the number of grids and finally I could have good looking steramplots (thanks to you). 

By the way, is there any way to overlay the streamplot on a polygon shapefile map? for instance, in the code below, countries polygon is plotted over streamplot. Streamplots stay under countries. Making the alfa = 0.5 is a temporary solution. 


```R
library(meteoForecast)
library(rasterVis)
library(sp)

download.file("http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip","ne_50m_admin_0_countries.zip", method = "curl")
unzip("ne_50m_admin_0_countries.zip", exdir = fl)
cntry <- readOGR(dsn = "./ne_50m_admin_0_countries",
                 layer = "ne_50m_admin_0_countries", stringsAsFactors = TRUE)

u <- getRaster('u', day = '2016-04-01', frames = 1)
v <- getRaster('v', day = '2016-04-01', frames = 1)
uv <- stack(u, v)

 streamplot(uv, isField = 'dXY', region = F,  droplet = list(pc = .1),
             xlab = "Longitude", ylab = "Latitude", lwd = 1.2,
             par.settings = streamTheme(
               panel.background = list(col = 'cornflowerblue'),
               symbol = brewer.pal(n = 9, name = 'Reds')), col = "blue",
             streamlet = list(L = 20)) +
  layer(sp.polygons(cntry, fill = 'antiquewhite', col = "black", alpha = 1))
```

**Comment by oscarperpinan** [comment]
Set `under = TRUE` in the `latticeExtra::layer` function. Extracted from the help page of this function:

> under : whether the layer should be drawn before the existing panel function. This defaults to TRUE in the convenience functions layer_() and glayer_().
