### ISSUE TITLE
Superscript on titles 

### ISSUE THREAD

**Issue by jcberny** [oscarperpinan/rastervis#36]
Would it be possible to add a superscript on the grid.text as the title of the scale?

For example:
grid::grid.text('Soil bulk density (kg m^3)'.......
Where the 3 should be over the m

**Comment by oscarperpinan** [comment]
This is easy thanks to [this commit](811e6391871d1f9d0bd025d2313819f23679ad44). For example:
`levelplot(r, colorkey = list(title = expression(m^3)))`
