### ISSUE TITLE
unexpected vector directions with vectorplot and `isField = TRUE` 

### ISSUE THREAD

**Issue by ashander** [oscarperpinan/rastervis#47]
Hi, Thanks for `rasterVis`! I'm having a small issue with `rasterVis_0.4`.

The example below produces vectors in the 2nd and 4th quadrant that aren't in the direction I expect (toward the origin).

```r
## simple example
library(rasterVis)
r <- raster(nrows=2, ncols=2, xmn=0, xmx=5, ymn=0, ymx=5)
set.seed(111)
values(r) <- runif(4, 0, 5)
dX <- r
values(dX) <- c(1.5, -1.5, 1.25, -2.7)
dY <- r
values(dY) <- c(-1.5, -1.5, 1.25, 2.7)
comp <- stack(list(dx=dX, dy=dY))
mag <- r
values(mag) <- sqrt(values(dX)^2 + values(dY)^2)
ang <- r
values(ang) <- atan2(x=values(dX), y=values(dY))
vf <- stack(list(mag=mag, slope=ang))
# plot(comp)
# plot(vf)
vectorplot(vf, isField=TRUE, units="radians", lwd=5, col='orange',
           par.settings=viridisTheme(), title="vf of mean net movement")
```

![image](https://user-images.githubusercontent.com/510776/27150752-4b7cf754-50fd-11e7-9825-cd92aecf49e4.png)

**Comment by petrelharp** [comment]
I think this is because:

1. cells are ordered left-right, top-bottom, so first is top left, second is top right
2. dX appears to be the vertical axis, dY appears to be the horizontal - switching x and y in `atan2` gets arrows as expected.

... I'm not sure why the latter is convention, however.

**Comment by ashander** [comment]
@petrelharp ah nice! couldn't quite wrap my head around your point 2 before I suggested a fix in #48 to match my expectations about the axes. looks like making the switch you suggest will fix my code with the stable version of `rasterVis`.

If Oscar chimes in with confirmation that this is the convention, I'll be happy to make a PR with an elaboration of this in the docs. (Unless it's already there and we missed it ;)

**Comment by oscarperpinan** [comment]
Hello,

1. The coordinates of your points are:
```
> dXY <- stack(dX, dY)
> coordinates(dXY)
        x    y
[1,] 1.25 3.75
[2,] 3.75 3.75
[3,] 1.25 1.25
[4,] 3.75 1.25
```
Thus, the first point is located at the top-left corner, the second point at the top-right corner, and so on. 

`vectorplot(dXY, isField = 'dXY', region = FALSE)`
![dxy](https://user-images.githubusercontent.com/1321370/27202642-a5ef9946-5222-11e7-8708-cc0adfae00b2.png)


2. On the one hand, the aspect angle is, by definition, [computed clockwise from due north](https://gis.stackexchange.com/questions/202988/in-rs-rasterterrain-function-which-way-is-north). Therefore:

```
> slope <- sqrt(dX^2 + dY^2)
> aspect <- atan2(dX, dY)
> sa <- stack(slope, aspect)
> vectorplot(sa, isField = TRUE, region = FALSE)
```
![sa](https://user-images.githubusercontent.com/1321370/27202718-e088cece-5222-11e7-9dfe-6d2f0838d0c0.png)

I will add a note in the help page to clarify this. Thanks!

**Comment by ashander** [comment]
Thanks! Makes sense that it was due to my unfamiliarity with `raster` / arcgis conventions. Thanks also for the more intuitive `isField='dXY'` interface, but a note on the help page would definitely clarify things.

PS to clarify an unrelated issue: the difference in vector length between the two plots is due to different defaults for `scaleSlope`. Adding the argument `scaleSlope=FALSE` to plot 2 will make them identical.
