### ISSUE TITLE
Get data from `gplot`

### ISSUE THREAD

**Issue by statnmap** [oscarperpinan/rastervis#52]
I like `gplot` function because this allows to plot big rasters without having to show all tiles.  
However, I sometimes need to plot layers below my raster object or plot 2 rasters one over the other. As far as I see it, `gplot` does not allow for this. Hence, I created a modified version of `gplot` to retrieve data in the _tidy_ way instead of the ggplot layer. This also allows me to clean it a little while removing NA values for instance and to be more flexible on my ggplots (changing names, levels, aesthetics, ...).  
I think that this function would have its place in {rasterVis} instead of my own [SDMSelect dev package](https://github.com/statnmap/SDMSelect) where it is currently.

```
#' Transform raster as data.frame to be later used with ggplot
#' Modified from rasterVis::gplot
#'
#' @param x A Raster* object
#' @param maxpixels Maximum number of pixels to use
#'
#' @details rasterVis::gplot is nice to plot a raster in a ggplot but
#' if you want to plot different rasters on the same plot, you are stuck.
#' If you want to add other information or transform your raster as a
#' category raster, you can not do it. With `SDMSelect::gplot_data`, you retrieve your
#' raster as a data.frame that can be modified as wanted using `dplyr` and
#' then plot in `ggplot` using `geom_tile`.
#' If Raster has levels, they will be joined to the final tibble.
#'
#' @export

gplot_data <- function(x, maxpixels = 50000)  {
  x <- raster::sampleRegular(x, maxpixels, asRaster = TRUE)
  coords <- raster::xyFromCell(x, seq_len(raster::ncell(x)))
  ## Extract values
  dat <- utils::stack(as.data.frame(raster::getValues(x)))
  names(dat) <- c('value', 'variable')

  dat <- dplyr::as.tbl(data.frame(coords, dat))

  if (!is.null(levels(x))) {
    dat <- dplyr::left_join(dat, levels(x)[[1]],
                            by = c("value" = "ID"))
  }
  dat
}
```

In my SDM Vignette, I have an example on how to use it then:

```
# Get partial raster data to plot in ggplot
pred.r.gg <- gplot_data(pred.r)
# Plot
ggplot() +
  geom_tile(
    data = dplyr::filter(pred.r.gg, variable == "resp.fit"), 
            aes(x = x, y = y, fill = value)) +
  scale_fill_gradient("Probability", low = 'yellow', high = 'blue') +
  coord_equal()
```

Tell me if you think, this could fit into {rasterVis} and if I can propose a PR.

**Comment by oscarperpinan** [comment]
Thanks for your proposal, but I don't want to include in `rasterVis` functions to extract data. The `raster` package provides several functions for this task, and it is the place where they have to available. Moreover, I would like to avoid additional dependencies. 
Anyway, I will try to improve the `qplot` function as soon as possible.
