### ISSUE TITLE
factor levels do not appear to be respected in levelplot()

### ISSUE THREAD

**Issue by dylanbeaudette** [oscarperpinan/rastervis#53]
Hi, 

Any idea why the following doesn't work? It seems like the colors and key should follow the levels specified in `rat$landcover`.

```r
r <- raster(nrow=10, ncol=10)
r[] = 1
r[51:100] = 3
r[3:6, 1:5] = 5
r <- ratify(r)

rat <- levels(r)[[1]]
rat$landcover <- factor(c('Pine', 'Oak', 'Meadow'), levels = c('Oak', 'Meadow', 'Pine'))
rat$class <- c('A1', 'B2', 'C3')
levels(r) <- rat

levelplot(r, col.regions=c('palegreen', 'midnightblue', 'indianred1'))
```

Thanks!

**Comment by oscarperpinan** [comment]
Hi,

The `Raster` objects produced by the `ratify` function include the levels in the RAT matrix, and are available through the `levels` function. Although the columns of this matrix can be factors with additional levels, I have not considered this option in the `levelplot` implementation.  

Thus, if you need additional levels, you have to create another column in the RAT matrix: 

```
rat$landcover2 <- c('Oak', 'Meadow', 'Pine')
levels(r) <- rat
levelplot(r, col.regions=c('palegreen', 'midnightblue', 'indianred1'), att = 'landcover2')

```

**Comment by oscarperpinan** [comment]
Closed for lack of additional comments.
