### ISSUE TITLE
is it possible to show tick scales on top right

### ISSUE THREAD

**Issue by earthcli** [oscarperpinan/rastervis#55]
scales = list(alternating = 3)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
levelplot(r,scales=scales)

whit it does not work?

**Comment by oscarperpinan** [comment]
The default value of the arguments `xscale` and `yscale` are `xscale.raster` and `yscale.raster`, respectively. In the help page of these functions you will find:
> ‘xscale.raster’ and yscale.raster suppress the right and top axis, respectively.  

Thus, the solution is to use alternative functions for these arguments. For example:

```
levelplot(r, scales = list(alternating = 3), 
          xscale = xscale.components.default, 
          yscale = yscale.components.default, 
          margin = FALSE)
```
