### ISSUE TITLE
How to customise bwplot?

### ISSUE THREAD

**Issue by rasenior** [oscarperpinan/rastervis#56]
Apologies if this is very trivial, but I cannot see from the documentation, website or FAQ section how to customise `bwplot`. 

The figure I'm making is for a manuscript, and the reviewers have asked if I can make the boxplot component clearer and if I can add the sampled raw data in the background. I would also like to change the fill of the violin component. I assumed some of these things were inherited from `lattice::bwplot`, but `color = "grey"`, for example, doesn't seem to do anything.

**Comment by oscarperpinan** [comment]
Hi.

Unfortunately the graphical parameters of `bwplot` are [hardcoded](https://github.com/oscarperpinan/rastervis/blob/master/R/bwplot.R#L22). I will fix this bad coding practice as soon as possible.

**Comment by oscarperpinan** [comment]
Hi @rasenior .
I have just made several changes in the `bwplot` code regarding your issue. Please, could you try it? I would appreciate your comments.
Sorry for the delay.

**Comment by rasenior** [comment]
This is super @oscarperpinan, thank you (and sorry for being slow to try it out). The only thing I'm struggling with now is that the raw points seem to be drawing in the foreground, thus obscuring the violin plots. It might also be useful to allow the raw points to be customised (e.g. change colour/size/alpha/jitter), but that's not urgent for me.

Thanks for the changes!

**Comment by oscarperpinan** [comment]
Sorry, I forgot to mention that I included a new `bwTheme` that allows for customization of the components of the `bwplot`:
```
          bwTheme(box.rectangle = list(col='black', fill = 'gray'),
             box.umbrella = list(col = 'black', lty = 1),
             plot.polygon = list(col = 'lightblue', alpha = 0.5),
             plot.symbol = list(cex = 0.5, alpha = 0.2),
             ...)
``` 
where the `plot.symbol` argument is a list whose components define the raw points when `draw.points = TRUE`.

**Comment by rasenior** [comment]
Ah I see! Great. I'm happy to close this issue now. Thanks again for all your work here.
