### ISSUE TITLE
Adding arrows to levelplot()

### ISSUE THREAD

**Issue by simon-tarr** [oscarperpinan/rastervis#57]
Sorry to post within the package's issues section but I was unable to get an answer on StackOverflow. I was hoping that the package author may know whether it is possible to add arrows between two points using `levelplot()`.

I would like to add some arrows to a categorical raster plot. Using Base R (on a non-ratified raster) as an example:

```
r <- raster(nrow=10, ncol=10, crs='+proj=utm +zone=1')
r[] = 1
r[51:100] = 3
r[3:6, 1:5] = 5

plot(r)

arrows(100, 50,
       0, 50, 
       length = 0.1, 
       lwd=2,
       col="red"
)
```
In levelplot you must first ratify your raster and add the appropriate levels:

```
r <- raster(nrow=10, ncol=10, crs='+proj=utm +zone=1')
r[] = 1
r[51:100] = 3
r[3:6, 1:5] = 5


r <- ratify(r)
rat <- levels(r)[[1]]
rat$landcover <- c('Pine', 'Oak', 'Meadow')
rat$class <- c('A1', 'B2', 'C3')
levels(r) <- rat

levelplot(r)
```
How can I add the red arrow (as shown in example 1) to the `levelplot()` shown in the second block of code?

The above question can be found [here](https://stackoverflow.com/questions/56257712/add-arrows-to-levelplot) if someone is able to answer and would like the sweet, sweet StackOverflow rep.

Thank you.

**Comment by oscarperpinan** [comment]
Hi, 

I have posted a solution [here](https://stackoverflow.com/a/56432982/964866).

**Comment by simon-tarr** [comment]
Hi @oscarperpinan thanks very much for the answer on SO. I've accepted it as solving my 'issue'. Cheers, Simon.
