### ISSUE TITLE
problem with levelplot for categorical data 

### ISSUE THREAD

**Issue by jamiemkass** [oscarperpinan/rastervis#64]
This wasn't an issue before, so it seems maybe the version update caused it? When plotting categorical data with factor rasters, the proper attribute from the levels table does not show in the legend -- instead, the ID category does. This happens even when you specify att = "some_name" to specify the column name.

Thanks,

Jamie

**Comment by oscarperpinan** [comment]
Thanks. I didn't spot it when reviewing the changes.
