### ISSUE TITLE
Excelente paquete. Saludos rOpenSpain

### ISSUE THREAD

**Issue by verajosemanuel** [oscarperpinan/rastervis#67]
Espectacular, realmente un gran paquete.
No se si conoces el proyecto rOpenSpain, donde tratamos de recopilar paquetes hechos en R por españoles o con contenido español

https://ropenspain.es/paquetes/

Te invitamos a unirte.
Saludos

**Comment by oscarperpinan** [comment]
Hola Jose Manuel.

Gracias por el comentario. 

Conozco rOpenSci, pero no sabía de la existencia de la rOpenSpain. Te agradezco la invitación, pero prefiero seguir sin cambios en rasterVis.

Saludos,

Oscar.
