### ISSUE TITLE
levelplot not working with terra 1.2.10

### ISSUE THREAD

**Issue by hzambran** [oscarperpinan/rastervis#70]
Dear Oscar,

I'm using `rasterVis_0.50.2`  and `terra_1.2-10`, and the function `levelplot` shows different figures for the sma raster data, depending on the raster data was read with `raster` or `terra` package:

```
f <- system.file("external/test.grd", package="raster")
## raster
r <- raster(f)
levelplot(r)
```

![rasterVis-raster](https://user-images.githubusercontent.com/2619297/122648384-10114980-d0f7-11eb-92f2-57690d43d5b3.png)

```
## terra
rt <- rast(f)
levelplot(rt)
```

![rasterVis-terra](https://user-images.githubusercontent.com/2619297/122648369-fec83d00-d0f6-11eb-8d7b-51d5180d9cd2.png)

and the image read with the `terra` package is not correct.

Is `rasterVis` compatible with `SpatRaster` objects?

**Comment by rhijmans** [comment]
It looks like this is caused by a change in a default setting in `terra` --- my bad. I have created a pull-request for Oscar to evaluate.

**Comment by hzambran** [comment]
Thank you very much !

**Comment by oscarperpinan** [comment]
Thanks @hzambran for your comment, and thanks @rhijmans for the pull request. Merged.

**Comment by tungmilan** [comment]
Thanks @oscarperpinan and @rhijmans ! Will you push this change to CRAN soon?

**Comment by rhijmans** [comment]
You can install the dev version with  `remotes::install_github("oscarperpinan/rastervis")`
