### ISSUE TITLE
Typo in levelplot() help section

### ISSUE THREAD

**Issue by anguswg-ucsb** [oscarperpinan/rastervis#74]
I'm not sure if this is where I should post this but I found a typo in the levelplot() help forums. 

In the **Arguments** section, under **"pretty, contour, region, label",** in the "**labels" description**, 
the word **"Tipically"** should be spelled **"Typically"**.

> labels: **_Tipically_** a logical indicating whether the labels are to be drawn (default is TRUE for contourplot), a character or expression vector giving the labels associated with the at values, or a list whose components define the labels and their graphical parameters. Read the help page of panel.levelplot for details.

Typos always bug me so I thought I'd pass it along :) 
Thank you for the package, its a good one. 

Cheers

**Comment by oscarperpinan** [comment]
Thanks!. Fixed now.
