### ISSUE TITLE
'subset' must be logical returned by vectorplot function

### ISSUE THREAD

**Issue by MilanFischer** [oscarperpinan/rastervis#77]
Hello,
I am trying  to reproduce the following example :

```
library(raster)
library(rasterVis)

proj <- CRS('+proj=longlat +datum=WGS84')
df <- expand.grid(x = seq(-2, 2, .01), y = seq(-2, 2, .01))

df$z <- with(df, (3*x^2 + y)*exp(-x^2-y^2))
r <- rasterFromXYZ(df, crs=proj)

vectorplot(r, par.settings=RdBuTheme())
```

however, I am receiving the following error:
`Error in subset.default(sa, 1) : 'subset' must be logical`

To try fixing it, I downloaded the package and changed the subset to raster::subset at all places where the subset function was used in the vectorplot function and compiled the package.  The reason is that the subset is applied on raster objects. After that, I received another error message:
`Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  :  length of 'dimnames' [1] not equal to array extent`

I am using Rstudio 2021.09.0, R x64 4.1.1, rasterVis_0.51.0 and  raster_3.5-2 on Windows 10 Pro.

Please, do you have any suggestion how to fix this?

Thanks,
Milan

**Comment by oscarperpinan** [comment]
Thanks for the issue. 

It is fixed now.

**Comment by MilanFischer** [comment]
Great, thanks for the fix. I just tested that and it works well!

Milan
