### ISSUE TITLE
2 questions about colorkey

### ISSUE THREAD

**Issue by tigerwang1998** [oscarperpinan/rastervis#80]
Hi，

I met 2 questions in this brilliant  package. 

Q1: How to reverse the colorkey? 

For example，I can use scale_fill_viridis(direction = -1) in ggplot ,but I don't know how to do this in levelplot.

Q2: The space of colorkey can't be modified.

`f <- system.file("external/test.grd", package="raster")`
`r=raster(f)`
```
levelplot(r, par.settings=viridisTheme,
          colorkey=list(space='right'))
```

I set the **space='right'** ,but the colorkey is  still on the bottom.

I will be very appreciated if you could give me an early reply！

**Comment by oscarperpinan** [comment]
Hello,

> Q1: How to reverse the colorkey?

Use `rev`. For example:

`myTheme <- rasterTheme(region=rev(magma(10)))`

> Q2: The space of colorkey can't be modified.

You have to disable the marginal graphics to customize the location of the color key. I have added a text in the help page of levelplot:

`levelplot(r, colorkey = list(space = "right"), margin = FALSE)`

**Comment by tigerwang1998** [comment]
您好，邮件已收到。
 久等不回或急事请电话联系。
