### ISSUE TITLE
'levelplot' not working with multi-layer files in 'terra' package

### ISSUE THREAD

**Issue by hzambran** [oscarperpinan/rastervis#83]
Dear Oscar and `rasterVis` users,

I just found that a code that was working some months ago, now stops working.

After tracing back the error, I realised that the error is due to some change in some recent version of `rasterVis`, because the `levelplot` function now is not working with raster files with more than 1 layer when using the `terra` package. 

A reproducible example is given below:

```
library(terra)
library(rasterVis)

# Create a SpatRaster from a file
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

# Creating a SpatRaster with 3 dummy bands
r3 <- c(r,r,r)

# This object is NOT plotted with levelplot
rasterVis::levelplot(r3)

```

It seems that the error is in the usage of the names of each layer.

This error does not happen when using the `raster` package:

```
library(raster)
library(rasterVis)

# Create a raster object from a file
f <- system.file("external/test.grd", package="raster")
r <- raster(f)

# Creating a Stack with 3 dummy bands
r3 <- stack(r,r,r)

# This object is correctly plotted with levelplot
rasterVis::levelplot(r3)
# Error in eval(i, data, env) : object 'elevation.1' not found
```

The output of my `sessionInfo()` is:

```
sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.3

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rasterVis_0.51.2 lattice_0.20-45  raster_3.5-15    sp_1.4-7        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3        codetools_0.2-18    png_0.1-7          
 [4] viridisLite_0.4.0   zoo_1.8-10          grid_4.2.0         
 [7] hexbin_1.28.2       latticeExtra_0.6-29 RColorBrewer_1.1-3 
[10] rgdal_1.5-31        jpeg_0.1-9          parallel_4.2.0     
[13] compiler_4.2.0      terra_1.5-21       

```

**Comment by oscarperpinan** [comment]
Thanks for the message. 
In my opinion, this should be solved in `terra`: the names of the `SpatRaster` object should be different, as in the `raster` package.

**Comment by hzambran** [comment]
I just realised that it is not always true that `levelplot` does not have any problem when the name of the layers are different:

```

library(terra)
library(rasterVis)

# Create a SpatRaster from a file
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

# Creating a SpatRaster with 3 dummy bands
r3 <- c(r,r,r)
names(r3) <- paste0("elev-", 10:12)
names(r3)
# "elev-10" "elev-11" "elev-12"

rasterVis::levelplot(r3)
#Error in eval(i, data, env) : object 'elev.10' not found
```

I guess that internally `levelplot` changes the '**-**' by "**.**" because the first is not an "_standard_" character, even if -to the best of my knowledge- "**-**" is an UTF-8 one.

What other character changes makes `levelplot` internally?

**Comment by oscarperpinan** [comment]
`levelplot` uses `make.names` to ensure valid names of the layers. 
https://github.com/oscarperpinan/rastervis/blob/5c3fea3d392bff2480b9a6070648283c71fbf3d9/R/levelplot.R#L36-L37

A similar approach is implemented in `raster::stack` with [`validNames`](https://github.com/rspatial/raster/blob/1947d6c2bda5d082135c43c69790930f3dedec08/R/stack.R#L87) but not in `terra::c`, as far as I know.

**Comment by hzambran** [comment]
Thank you very much for the useful reply.

In order to make `levelplot` fully compatible with `terra`, would it be possible to use `unique = FALSE`:

`nms <- make.names(nms, unique = FALSE)`

**Comment by oscarperpinan** [comment]
No, because the rest of the code needs the names to be unique. For example:

https://github.com/oscarperpinan/rastervis/blob/0aafb66a50b5f1073f44f9446b74eb5555fed93e/R/levelplot.R#L256-L258

**Comment by hzambran** [comment]
Thank you very much.
