### ISSUE TITLE
Argument aspect in rasterVis::levelplot

### ISSUE THREAD

**Issue by Schuch666** [oscarperpinan/rastervis#84]
I'm trying to plot changing the aspect (using aspect = 'fill') but I got this error

Error in levelplot.formula(form, data = df, scales = scales, aspect = aspect,  : 
  formal argument "aspect" matched by multiple actual arguments

I realized that aspect is calculated inside levelPlot and passed to levelplot.formula. Is there a way to provide this information for levelplot.formula that produce the plot?

Thanks

**Comment by oscarperpinan** [comment]
You can modify it after creating the `trellis` object:
```
library(rasterVis)
library(raster)
     
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
p <- levelplot(r)

p$aspect.fill <- TRUE

p
```

However, I do not recommend to change it. The aspect ratio is calculated inside `levelplot` to provide an accurate representation of the data.
