### ISSUE TITLE
a redundant legend title

### ISSUE THREAD

**Issue by tigerwang1998** [oscarperpinan/rastervis#86]
Hi,Oscar
I am sorry to ask again.
But when I add legend title, it always occurs a redundant legend title.

For example,
```
library(rasterVis)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
levelplot(r, margin=F,colorkey = list(title = "correlation coefficient",
                             space="right"))
```
![image](https://user-images.githubusercontent.com/50581765/167925468-aa9ae41c-4e99-4fe8-9e8d-2f89f4909f77.png)

There is a redundant and small legend title,which makes a blank between title and figure.
How to retain the main legend title and remove the tiny legend title?

**Comment by oscarperpinan** [comment]
Thanks. It is a bug in the code.

**Comment by oscarperpinan** [comment]
There is an example in the help page:

```
levelplot(r, margin = FALSE,
          colorkey = list(title = list("[m]",
                                       cex = 1,
                                       fontface = "bold",
                                       col = "red")
                          ))
```

**Comment by tigerwang1998** [comment]
But how to adjust the colorkey(legend) title to the right?
Just like ` title=list(rot=90,space="right")`
![image](https://user-images.githubusercontent.com/50581765/169161686-57b469ab-494a-45b1-8bce-804199f19abc.png)

**Comment by oscarperpinan** [comment]
Please, update the package with the last commit and try this example:
```
levelplot(r, margin = FALSE,
          colorkey = list(title = "[m]",
                          space = "right",
                          title.control = list(side = "right")))

```
