### ISSUE TITLE
can't get rid of grey peaks around continuous levelplot

### ISSUE THREAD

**Issue by cperk** [oscarperpinan/rastervis#88]
How do I suppress these? They make it very difficult to fit several levelplots in a multi-panel plot.

**Comment by oscarperpinan** [comment]
Please, post a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by cperk** [comment]
Sure! Using your example from this tutorial:

[https://oscarperpinan.github.io/rastervis/](url)


library(raster)
library(rasterVis)

```
##Solar irradiation data from CMSAF 
old <- setwd(tempdir())
download.file('https://raw.github.com/oscarperpinan/spacetime-vis/master/data/SISmm2008_CMSAF.zip',
              'SISmm2008_CMSAF.zip', method='wget')
unzip('SISmm2008_CMSAF.zip')

listFich <- dir(pattern='\\.nc')
stackSIS <- stack(listFich)
stackSIS <- stackSIS * 24 ##from irradiance (W/m2) to irradiation Wh/m2

idx <- seq(as.Date('2008-01-15'), as.Date('2008-12-15'), 'month')

SISmm <- setZ(stackSIS, idx)
names(SISmm) <- month.abb

setwd(old)

levelplot(SISmm, layers = 1, margin = list(FUN = 'median'), contour=TRUE)
```

I want to suppress the gray "peaks" surrounding the plot:

![Screen Shot 2022-06-02 at 7 00 00 PM](https://user-images.githubusercontent.com/21315115/171751824-8e69fa3b-1850-4543-9f39-5b2200001667.png)

**Comment by oscarperpinan** [comment]
Use `margin = FALSE`
