### ISSUE TITLE
`levelplot()`: Add support for alternate ID name for SpatRaster

### ISSUE THREAD

**Issue by brownag** [oscarperpinan/rastervis#90]
Hi Oscar!

I noticed that in `levelplot()` if there is no column in the RAT called `"ID"` then `ratID` is NULL.
https://github.com/oscarperpinan/rastervis/blob/f2abe81cb68f5177aec96622b619c8a5c8454cb9/R/levelplot.R#L488

I think when rat$ID is NULL one could assume the first column (`rat[[1]]`) contains the ID (maybe), or use `seq_len(nrow(rat))` to calculate one (guaranteed unique and continuous)  Tagging @rhijmans FYI and to see if you have input

Here is an example where a "valid"** categorical SpatRaster has no column in RAT called `"ID"` that currently fails.
``` r
library(terra)
#> terra 1.6.11
cls <- data.frame(id =    c(12345,   12346,   12350),
                  cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$id, ncell(r), replace = TRUE)
levels(r) <- cls
r
#> class       : SpatRaster 
#> dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#> resolution  : 36, 18  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> source      : memory 
#> categories  : cover 
#> name        :  cover 
#> min value   : forest 
#> max value   :  urban

library(rasterVis)
#> Loading required package: lattice
levelplot(r)
#> Error in x@ptr$replaceValues(from, to, 0, keepcats, opt): Not compatible with requested type: [type=NULL; target=double].
```

**There are some parallel issues in the recent terra versions 1.6+ (https://github.com/rspatial/terra/issues/787 https://github.com/rspatial/terra/issues/788).

I just saw a need/opportunity to generalize the hardcoded `$ID` in rasterVis levelplot SpatRaster method so wanted to see what you thought about this.

**Comment by oscarperpinan** [comment]
Thanks for this issue. I have modified the code to generalize the extraction of the `ID` values.
