### ISSUE TITLE
levelplot(<SpatRaster>) and default behavior of `subst()` w/ terra 1.6-x+ 

### ISSUE THREAD

**Issue by brownag** [oscarperpinan/rastervis#92]
In terra 1.6-x the default behavior of `subst()` was changed such that it expects labels not the "raw values" of the raster in the `from` argument. 

``` r
library(terra)
#> terra 1.6.27
library(rasterVis)
#> Loading required package: lattice
cls <- data.frame(id =    c(12345,   12346,   12350),
                  cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$id, ncell(r), replace = TRUE)
levels(r) <- cls
levelplot(r)
#> Warning: [subst] all 'from' values are missing, returning a copy of 'x'
#> Error in Summary.factor(structure(c(3L, 2L, 3L, 1L, 3L, 2L, 2L, 3L, 1L, : 'range' not meaningful for factors
```

Based on how I understand the problem, there are three options to fix this:
 - unset levels with `levels(objectSample) <- NULL` before calling `subst()`
 - use `subst(..., raw = TRUE)` (supported in terra >1.6-11)
 - use `classify(objectSample, cbind(ratID, seq_along(ratID)))` (always operates on "raw" values; should be backward compatible)

See discussion in https://github.com/rspatial/terra/issues/787 for more info.

**Comment by oscarperpinan** [comment]
Thanks. Fixed now, although the colorkey needs to be improved.
