### ISSUE TITLE
maptools retirement

### ISSUE THREAD

**Issue by rsbivand** [oscarperpinan/rastervis#93]
@oscarperpinan could I please ask for your view on whether functions you contributed to **maptools** should be deprecated and moved to another package, or simply be allowed to be archived (see https://r-spatial.org/r/2022/04/12/evolution.html)? 

I'm thinking of https://r-forge.r-project.org/scm/viewvc.php/pkg/R/lineLabel.R?view=markup&root=maptools and https://r-forge.r-project.org/scm/viewvc.php/pkg/R/pointLabelLattice.R?view=markup&root=maptools and their help files. Are you still using these functions? 

Using pkgapi https://github.com/r-lib/pkgapi I have  not found any uses in package code, but you may know of other uses.

**Comment by oscarperpinan** [comment]
Hi Roger,

Thanks for the reminder. 

I only use these functions in [this book](https://oscarperpinan.github.io/bookvis/). I don't have a package to move them, so I have opened a [new repository ](https://github.com/oscarperpinan/label)for them and their help files. Therefore, their code in `maptools`  can be archived.

Thanks for your work.

**Comment by rsbivand** [comment]
Thanks; deprecation committed svn rev. 403-4.
