### ISSUE TITLE
layer overwriting if saving levelplot to list in loop

### ISSUE THREAD

**Issue by JLKWren** [oscarperpinan/rastervis#94]
Hi, 

I'm not sure this is the correct place to ask but I have a problem that I can't find a solution to online. I am trying to make multiple levelplots inside a loop and save them to a list as I go. This works great for the levelplot portion, but when I add a layer only the data from the last loop shows on all the figures, no matter when in the loop they were saved to the list. I have included a reproducible example below. I took it from your FAQ document and modified it slightly by adding a layer and saving to a list. If I print inside the loop (the commented out line) the point is in different locations as it should be, but if I print it outside the loop the points are all in the same spot.

```
r <- r2 <- raster()
r[] <- runif(ncell(r))
r2[] <- 1:10
s <- stack(r, r2, 10*r+r2, 10*r-r2)
nl <- nlayers(s)
m <- matrix(1:nl, nrow=2)
themes <- list(RdBuTheme(), BTCTheme(), GrTheme(), PuOrTheme())

my.points <- data.frame(runif(4,-100,100), runif(4,-50,50))
p <- list()

for (i in 1:nl){
  p[[i]] <- levelplot(s, layers=i,
                 par.settings=themes[[i]],
                 margin=FALSE) + layer(panel.points(my.points[i,], cex=5, col='white'))
}
print(p)
```

I'm trying to make plots that combine not only levelplots but other graphics as well so I need to save the levelplots to a list that I can call later.

Is there a solution to this problem? It might be so obvious I'm not seeing it so any help you can provide is greatly appreciated. 

Thank you, 
Johanna

**Comment by oscarperpinan** [comment]
Hello Johanna,

When you print outside the loop, you are calling the `xyplot.list` method from the latticeExtra package (more information here https://latticeextra.r-forge.r-project.org/man/c.trellis.html).

This method does not print directly but first combines the elements of the list. 

I do not see a solution other than print inside the loop.

**Comment by JLKWren** [comment]
Hi Oscar, 

Thanks so much for the reply!

~johanna
