### ISSUE TITLE
levelplot do not show longitude and latitude units

### ISSUE THREAD

**Issue by tigerwang1998** [oscarperpinan/rastervis#95]
Hi Oscar,
I met this situation, I don't know if it occurs for everyone.
```
library(raster)
library(rasterVis)
r <- system.file("external/test.grd", package="raster")
rr <- raster(r) %>% projectRaster(crs='+init=epsg:4326',
                                  method = 'bilinear')
levelplot(rr)
```
![image](https://user-images.githubusercontent.com/50581765/204749451-5de44788-d153-45e4-817a-db771d66e850.png)

**Comment by oscarperpinan** [comment]
If you use the native pipe operator `|>` the axis are correctly displayed:

```
rr <- raster(r) |> projectRaster(crs='+init=epsg:4326',
                                  method = 'bilinear')
```

**Comment by tigerwang1998** [comment]
Thanks!
I reloaded the codes in my question. the result is interesting.
It displayed correctly.
But the truth is that when I load `levelplot(rr)` before, it couldn't display correctly.
