### ISSUE TITLE
Categorical values not displayed on legend

### ISSUE THREAD

**Issue by FAmorim81** [oscarperpinan/rastervis#97]
Dear Oscar,

I'm trying to use `levelplot` to plot land cover map with categorical variable, and I can't get it to work. I have a RAT table with multiple variables one of which is the categorical classes, but no matter what I set as `att` the output of the legend is always a numeric value. In fact I tried the example in the reference manual (copied below) and I also get a numeric output.

```
r <- raster(nrow=10, ncol=10)
r[] = 1
r[51:100] = 3
r[3:6, 1:5] = 5
r <- ratify(r)
rat <- levels(r)[[1]]
rat$landcover <- c('Pine', 'Oak', 'Meadow')
rat$class <- c('A1', 'B2', 'C3')
levels(r) <- rat
r
levelplot(r, col.regions=c('palegreen', 'midnightblue', 'indianred1'))
## with 'att' you can choose another variable from the RAT
levelplot(r, att=2, col.regions=c('palegreen', 'midnightblue', 'indianred1'))
levelplot(r, att='class', col.regions=c('palegreen', 'midnightblue', 'indianred1'))
```

![image](https://user-images.githubusercontent.com/86807797/207910852-d5c9878f-f6e1-491c-8a91-362ba59e3238.png)

Any idea what I could be doing wrong?

Thanks in advance.
_________________
Windows 11 64x
R version 4.2.2 (x86_64)
RStudio 2022.07.2
rasterVis 0.51.4

**Comment by oscarperpinan** [comment]
Hello,

Thanks. It is a bug due to an [old commit](https://github.com/oscarperpinan/rastervis/commit/6e10f55f63465cb04c21bd2a9d6efbb8ead2d785). Fixed now. You should install the development version.

**Comment by tigerwang1998** [comment]
> Hello,
> 
> Thanks. It is a bug due to an [old commit](https://github.com/oscarperpinan/rastervis/commit/6e10f55f63465cb04c21bd2a9d6efbb8ead2d785). Fixed now. You should install the development version.

Hello, oscar

Could you tell me where should I install the development version? I reinstalled this package from CRAN, but it still goes wrong.
